version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 214939106712.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - sudo systemctl status docker
      - sudo systemctl start docker
      - docker build -t nodejs-app-repo .
      - docker tag nodejs-app-repo:latest 214939106712.dkr.ecr.us-east-1.amazonaws.com/nodejs-app-repo:latest
  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push 214939106712.dkr.ecr.us-east-1.amazonaws.com/nodejs-app-repo:latest
