version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
  build:
    commands:
      - echo Building Docker image...
      - docker build -t nodejs-app-repo .
      - docker tag nodejs-app-repo:latest public.ecr.aws/m5l8f7s0/nodejs-app-repo:latest
  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push public.ecr.aws/m5l8f7s0/nodejs-app-repo:latest

